name: "Secrets to env"
description: "Generate env files from repository secrets"
inputs:
  secrets:
    description: "json string of github repository secrets"
    required: true
  secrets_env:
    description: ""
    required: true
  prefix_dev:
    description: ""
    default: "__DEV__"
    required: false
  file_name_dev:
    description: ""
    default: ".env.dev"
    required: false
  prefix_stag:
    description: ""
    default: "__STAG__"
    required: false
  file_name_stag:
    description: ""
    default: ".env.stag"
    required: false
  prefix_prod:
    description: ""
    default: "__PROD__"
    required: false
  file_name_prod:
    description: ""
    default: ".env"
    required: false
  overwrite_prod:
    description: ""
    default: "false"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
